export const banks = {
  "Banco de Bogotá": 1,
  "Banco BBVA": 2,
  "Banco Davivienda": 3,
  "Banco de Occidente": 4,
  Bancolombia: 5,
  "Banco AV Villas": 6,
  "Banco Caja Social": 7,
  "Banco Falabella": 8,
  Ban100: 9,
  "Banco Popular": 10,
  Bancoomeva: 11,
  "Bank of America": 12,
  Daviplata: 13,
  Itau: 14,
  "Lulo Bank": 15,
  Nequi: 16,
  Pibank: 17,
  Produbanco: 18,
  "Scotiabank Colpatria": 19,
  RappiPay: 20
}
